{% set name = "tintx" %}
{% set version = "2025.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tintx-{{ version }}.tar.gz
  sha256: 596984c692c87d6128cc576313439492edc1bd481f3d2104354a3ca32e0c4d2b

build:
  entry_points:
    - tintx = tintx.cli:tintx
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2
    - pip
  run:
    - python >={{ python_min }}
    - cartopy
    - cftime
    - click
    - dask-core
    - geopandas
    - matplotlib-base
    - netcdf4
    - numpy <2.0
    - pandas
    - rasterio
    - scipy
    - shapely
    - pytables
    - tqdm
    - typing_extensions
    - xarray

test:
  imports:
    - tintx
  commands:
    - pip check
    - tintx --help
  requires:
    - python {{ python_min }}
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/antarcticrainforest/tintX
  summary: Tracking facility to track rainfall and other non-continous data.
  dev_url: https://github.com/antarcticrainforest/tintX
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - antarcticrainforest
    - kmuehlbauer
