{% set name = "tintx" %}
{% set version = "2024.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tintx-{{ version }}.tar.gz
  sha256: 09ca508af9d8df8d4f39f2c06a4570593a908f09a091b1ecb131149ac9a5e53f

build:
  entry_points:
    - tintx = tintx.cli:tintx
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - flit-core >=3.2
    - pip
  run:
    - python >=3.8
    - cartopy
    - click
    - cftime
    - dask-core
    - geopandas
    - matplotlib-base
    - netcdf4
    - numpy <2.0
    - pandas
    - pytables
    - rasterio
    - scipy
    - shapely
    - tqdm
    - typing-extensions
    - xarray

test:
  imports:
    - tintx
  commands:
    - pip check
    - tintx --help
  requires:
    - pip

about:
  home: https://github.com/antarcticrainforest/tintX
  summary: Tracking facility to track rainfall and other non-continous data.
  dev_url: https://github.com/antarcticrainforest/tintX
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - antarcticrainforest
